Document: ia-bin-tools
Title: Debian ia-bin-tools Manual
Author: <insert document author here>
Abstract: This manual describes what ia-bin-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ia-bin-tools/ia-bin-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/ia-bin-tools/ia-bin-tools.ps.gz

Format: text
Files: /usr/share/doc/ia-bin-tools/ia-bin-tools.text.gz

Format: HTML
Index: /usr/share/doc/ia-bin-tools/html/index.html
Files: /usr/share/doc/ia-bin-tools/html/*.html
